asyncapi/conference-website

- .gitignore
- site/index.html
- sources/pug/pages/index.pug
- sources/pug/sections/_footer-classic.pug
- Some grammar fixes thanks to hints from @bszwarc 
- Fix of counter issue in Safari. This was the fix, date format from `data-to="2020-04-22 10:00:00"` to `data-to="04/22/2020 10:00:00"` Oh my, Safari. Fixing issue for a browser with [3y old instruction](https://www.coditty.com/code/javascript-new-date-not-working-on-ie-and-safari) doesn't give a good opinion about the browser
> fix: for broken counter in safari

- site/index.html
- sources/pug/sections/_section-swiper-slider-modern.pug
It replaces the video with the "miroservices" fix.
> Fix promo video

- site/index.html
- sources/pug/pages/index.pug
- sources/pug/sections/_section-swiper-slider-modern.pug
> Remove CFP

- sources/pug/pages/index.pug
> Fix links on talks

- sources/pug/sections/_footer-classic.pug
Adds a link to the code of conduct to the footer.
> Add code of conduct

- sources/pug/sections/_section-swiper-slider-modern.pug
- set event to start at 11 not 10
> fix: set event to start at 11 not 10

- gulpfile.js
> fix: include attachments dir in build

- package.json
- site/css/style.css
- sources/pug/pages/index.pug
- sources/pug/sections/_footer-classic.pug
- sources/pug/sections/_section-swiper-slider-modern.pug
Fck that was... 😅 Next year we hire an agency 😄 
- changed link to code of conduct as for the conference we need to follow LF one
- I'm not sure why css changes are done so bad, I added only this:
```css
ul,
ol {
list-style: none;
margin: 0;
}
ul li {
list-style-type: circle;
}
```
instead of:
```css
ul,
ol {
list-style: none;
padding: 0;
margin: 0;
}
ul li,
```
I just wanted nice bullet points and as a result it exploded 🤯 Anyway, works on my local like a charm 😄
> feat: new website version

- sources/pug/sections/_section-swiper-slider-modern.pug
> chore: add info about new event to old website

- sources/pug/pages/index.pug
Enhanced list 2 of solutions that can help AsyncAPI Community
> chore: enhanced second list item in hackathon description

- sources/pug/pages/index.pug
- sources/pug/sections/_section-swiper-slider-modern.pug
fixing Lukazs typos cause someone has to :D
> chore: fixing Lukazs typos

- sources/pug/_skeleton.pug
- sources/pug/pages/index.pug
https://deploy-preview-70--peaceful-ramanujan-288045.netlify.app/#schedule
> chore: add conference schedule

- sources/pug/sections/_section-swiper-slider-modern.pug
Add links to live streaming of 1st day conference
> feat: 1 day conference links

- sources/pug/sections/_section-swiper-slider-modern.pug
Update links for 2 day of conference
> feat: update links for 2 day of conference

- sources/pug/sections/_section-swiper-slider-modern.pug
Update links for 3 day of conference.
> feat: update links for 3 day of conference

- sources/pug/sections/_section-swiper-slider-modern.pug
> feat: add links to recordings

- components/Form/form.js
- components/Form/stepThree.js
Signed-off-by: akshatnema <20bcs022@iiitdmj.ac.in>
This PR targets to make a option available for the virtual users to select the Virtual Online meeting option in Location
> fix: virtual meetings option added in Location

- components/Button/button.js
- components/Footer/footer.js
- components/Header/header.js
- package-lock.json
- package.json
- yarn.lock
Added conference banner with YT livestream - like in https://github.com/asyncapi/website/pull/1070
cc @derberg @AceTheCreator 
Example:
> feat: add YT livestream preview

- README.md
- Improved the readme file to make it easy for new contributors to locally install the website
Resolves #128
> docs: enhanced the readme file

- components/Form/subscription.js
Fixed subscription form bad request
> fix: fixed netlify form

- components/Form/stepFour.js
Fixed broken excel api req link
> fix: fixed broken xls link

- components/Form/stepFour.js
> fix: fixed broken api link

- components/Navbar/navbar.js
enhanced the dropdown 
fixes #161
> fix: enhancements

- components/Header/header.js
- config/speakers.json
> feat: update the ticket link

- components/Agenda/agenda.js
- components/Speaker/speaker.js
- config/speakers.json
- pages/venue/[id].js
> feat: add agenda component

- components/Header/header.js
> feat: fix ticket button

- components/Venue/venue.js
- styles/globals.css
- Before:
[Implement visual states for images on location cards (hovered and clicked) · Issue #170 · asyncapi_conference-website.webm](https://github.com/asyncapi/conference-website/assets/96797205/fa6c348d-f648-4f0b-b52b-18c35498bb55)
- After:
https://github.com/asyncapi/conference-website/assets/96797205/245e5a5a-9c24-4fcd-aab0-435b16fc2a38
Kept the animation minimalistic and not flashy so in to blend with the theme and for a good user experience
Fixes #170
> feat: adds hover effect

- components/Agenda/agenda.js
- components/Countdown/countdown.js
- components/Header/header.js
Due to these changes, we can now include multiple speakers for one topic.
> feat: added support for multiple speaker agenda

- pages/index.js
- pages/venue/[id].js
Fixed the `Apply as a Speaker` button to work as expected.
Fixes #179 
cc @AceTheCreator @thulieblack
> fix: fixed apply as a speaker button in Paris Conference page

- config/speakers.json
source of info https://www.linkedin.com/in/jtpollock/
> chore: update info about Jeff Pollock that speaks in Madrid

- config/speakers.json
- ...
- ...
- ...
Related to #187
> fix: update some talk times in speakers.json

- components/Form/paper.js
- components/Header/header.js
- config/city-lists.json
- config/speakers.json
update and add the registration link for Madrid
> feat: update links

- components/Form/paper.js
- components/Header/header.js
- config/city-lists.json
- config/speakers.json
This reverts commit 0f8e96e3f24bcb949808e66e77a51b06af887372.
- ...
- ...
- ...
> revert: update links (#216)

- components/Form/paper.js
- components/Header/header.js
- config/city-lists.json
- config/speakers.json
> feat: update Madrid links

- config/speakers.json
Remove Alexis Sanchez from Speakers list and add back Alejandra Quetzalli
I added back the two breaks in the afternoon.
> fix: update speakers.json

- components/Header/header.js
- config/city-lists.json
> feat: added Madrid livestream link

- components/Countdown/countdown.js
- components/Header/header.js
- config/city-lists.json
- config/speakers.json
- pages/venue/[id].js
Updated the website with latest information :)
> feat: updated website with latest info

- config/speakers.json
Add details for the Bengaluru conf and agenda
> feat: add bangalore details

- package-lock.json
- package.json
Reverts asyncapi/conference-website#238
> chore(deps): revert bump next from 12.3.4 to 13.5.0

- components/Header/header.js
- config/city-lists.json
- config/speakers.json
> feat: update latest info

- components/Navbar/navbar.js
> style: hover effect on navbar dropdown links

- components/About/about.js
fixes #280 
- Fixes the overflowing out of buttons in about section
**Video of Changes:**
https://github.com/asyncapi/conference-website/assets/77102885/8bb1380e-c4a7-4bd1-9435-3a9ec5a9fadb
> fix: alignment of about the event buttons

- CODEOWNERS
> chore: added codeowners file

- components/Venue/venue.js
fixes #269 
- Added Link navigation when click on particular venue tab
**Video of Changes**
https://github.com/asyncapi/conference-website/assets/77102885/4b998d72-1dee-41a0-850c-0dfee1cc34fd
> fix: added venue link navigation

- components/Form/subscription.js
- pages/index.js
- Added  back the subscribe section from AACoT'23
Resolves: #298
> feat: added Subscribe section

- tailwind.config.js
- Cleared the warnings in the console
- Utilised https://github.com/tailwindlabs/tailwindcss/discussions/11127
Resolves: #294
> feat: cleared warnings according to mentioned resources

- components/announcement.js
- config/city-lists.json
- Removed CFP for Helsinki 
- Annouced London cfp
> feat: helsinki cfp update

- pages/editions/index.js
> fix: the card responsiveness at medium screen (in past edition page)

- components/Agenda/agenda.js
- components/Dropdown/dropdown.js
- components/Speaker/speaker.js
- components/Typography/paragraph.js
- components/Venue/venue.js
- config/city-lists.json
- config/speakers.json
- package-lock.json
- pages/index.js
- pages/venue/[id].js
- styles/globals.css
Added the list of speakers and their respective agendas
cc @thulieblack
> feat: added helsinki speakers and agenda

- config/speakers.json
> feat: add london speakers

- config/city-lists.json
- config/speakers.json
add agenda for AACoT'24 London
> feat: add london agenda

- components/Form/subscription.js
- package-lock.json
- pages/index.js
The subscription component name was misspelled as "Subcription". This commit fixes the typo and updates the component styles to improve the layout on different screen sizes.
- ...
- ...
- ...
Resolves #342
> fix: update subscription component name and styles

- config/speakers.json
Update the times for the agenda
> feat: update agenda times

- styles/globals.css
This PR addresses issue #356 by fixing the hover effect on the specified button.
[issue-356.webm](https://github.com/user-attachments/assets/5b3b13f1-d967-4bbc-b483-eeedecea5732)
-Bug fix
1.Go to Register Button
2.Hover it
3.after hovering , you will see the changes
> fix:  Fix Hover Effect on Button#356

- config/city-lists.json
> fix: removed the button in online edition

- config/speakers.json
> feat: add title and adjust time

- config/speakers.json
> feat: correct title

- components/Sponsors/sponsors.js
- pages/index.js
Added sponsor's website links to their respective logo
**Related Issue**
Fixes #446
> fix: add Links to sponsors Images

- CODEOWNERS
Adding @ashmit-coder in the codeowners.
> feat: add ashmit-coder as maintainer

- config/speakers.json
Add Hugo as co-speaker to Laurent's session
> feat: add co-speaker

- config/speakers.json
Change Julien and Alessandro's session title
> feat: change Julien's session's title

- config/city-lists.json
> fix: date/time format for online edition

- config/city-lists.json
- config/links.json
Update ticket section and add link to Paris slide folder
> feat: add paris slides link

- README.md
-Added Change Directory Command in Readme file 
Fixed #540 
Solved : -
> docs: add cd conference-website in readme file

- components/Sponsors/sponsors.js
- components/Venue/venue.js
- pages/index.js
Fixes #492
Add hover transform effects to card components to enhance user experience and visual appeal.
* **components/Venue/venue.js**
* Add hover transform effect to the card component to scale up smoothly when hovered over.
* Update the map button to change background color on hover.
* **components/Sponsors/sponsors.js**
* Update heading styles to use a consistent text color.
* **pages/index.js**
* Update the Sponsors component with new event and financial sponsor images and URLs.
> feat: add hover transform effect to card components

- pages/index.js
> fix: bug fixes for logo in homescreen

- config/city-lists.json
- config/speakers.json
Add talk agenda fro Singapore
CFP for Bangalore
> feat: add agenda for singapore

- config/cfp-data.json
- config/city-lists.json
- pages/api/speakers/register/index.js
- pages/venue/[id].js
> feat: change to sheet name to activate cfp

- components/Tickets/ticketCards.js
Add the ticket links for Singapore
> feat: add Singapore tickets 

- components/Tickets/ticketCards.js
> feat: ticket card automation as per current date

- components/Venue/venue.js
> fix: venue cards date misalignment

- config/city-lists.json
> feat: add lagos venue location

- components/Tickets/ticketCards.js
- config/city-lists.json
- config/speakers.json
- Add playlist for Singapore
- Add agenda draft for Munich
- Afdd Lagos registration link
> feat: add conference details

- components/announcement.tsx
- config/agenda.json
- config/city-lists.json
- config/speakers.json
- next-env.d.ts
- Add Lagos Agenda
- Add Paris First Speaker
- CFP Clean-up
> feat: add Lagos agenda

- components/Tickets/tickets.tsx
- config/speakers.json
- config/tickets.json
Add Free Community Tickets for London
> feat: add london tickets

- config/agenda.json
- config/city-lists.json
> feat: add the London Agenda
