- site/_redirects
Make redirect point to conference.asyncapi.com instead.
> fix: redirect to conference.asyncapi.com instead

- sources/pug/pages/index.pug
- sources/pug/sections/_section-swiper-slider-modern.pug
We should display in one place link to all the accounts where live stream will be available.
Opened for suggestions how to improve it. I can even close this PR in favour of something different.
My only strong opinion is that these should be links and not embedded video for example from YouTube as taking users to the specific platform to our account could convert into a "follow"
I also added info about winners of the hackathon
> feat: remove registration and add links to streams

- components/Form/form.js
- components/Header/header.js
This PR targets to add the width on the SVG (Patterns) to correct the view of the website in the FIrefox browser.
**Note:** Please ignore the slight change in the width of the Patterns as the width classes of the Tailwind are added to the Patterns.
> fix: added width to SVG

- config/speakers.json
Fawaz will no longer be participating as a speaker in Madrid, This PR will update the speakers section.
> feat: remove Fawaz from madrid speaker

- config/speakers.json
add the speakers for AACoT London
solve #168
> feat: add london speakers

- components/Agenda/agenda.js
- components/Speaker/speaker.js
- config/speakers.json
- pages/venue/[id].js
Implemented the agenda component and rendered the conference agenda for the London Edition. 
cc @thulieblack @derberg @Mayaleeeee 
resolves #162
> feat: add agenda component

- components/Header/header.js
- Made the font bold, increased text-size, line-height and letter-spacing
- Used available classes rather than going for custom css class
- Before:
- Applying custom-class as provided here 
https://github.com/asyncapi/conference-website/issues/175#issue-1870427927
- Applying Pre-Defined Class (Current):
Decided to stick with the last layout as it appears more clean but if required, I'd change it as suggested
Fixes #175
> fix: header sizing

- config/city-lists.json
- pages/venue/[id].js
added button on venue page to buy ticket 
fixes #185
> feat: get ticket button added

- components/Dropdown/dropdown.js
- config/speakers.json
- pages/index.js
- styles/globals.css
Add all speakers button
solves https://github.com/asyncapi/conference-website/issues/163
> feat: add all speakers button

- components/Form/subscription.js
- package-lock.json
fixes #217 
hey, @asyncapi-bot  I have modified the subscription button by using the existing Button component so it will have same styling like other buttons in the app and i have also provided relevant top margin.
I had also updated caniuse-lite to it's latest version as otherwise it was not working.
I am new to open source and I enjoyed working on this issue, hope you like my solution.
Please let me know your thoughts and suggestions.
> fix: subscription button modified #217

- pages/index.js
- Remove duplicate speakers from all speaker sections
Resolves  #239
> fix: remove duplicate speakers

- components/Navbar/navbar.js
Description :
Fixed the part where the venue sub menu on the navbar was not closing when clicked anywhere but inside the menu.
Related issue(s) :
Resolves #205
> fix: fixed the venue sub menu not closing

- config/speakers.json
> feat: update-agenda

- components/Header/header.js
- config/city-lists.json
- config/links.json
- config/speakers.json
1. Add Resource Hub Page with a list of all the links:
- Blog
- Recordings
- Slides
2. Add slides link to London and Paris pages
> feat: update 2023 website

- components/Footer/footer.js
fixes #268 
- Fixes the responsiveness of footer section in mobile
**Video of changes:**
https://github.com/asyncapi/conference-website/assets/77102885/4c120b81-b9b6-4b46-8bc5-2f957e6927d0
> fix: footer section responsiveness

- components/Navbar/navDrop.js
- components/Navbar/navbar.js
This pull request updates the margin and padding to fix the alignment of the hero section on the website.
**Related issue(s)** Fixes #267
|Earlier|Now|
|---|---|
|![image](https://github.com/asyncapi/conference-website/assets/96991785/0ccdaf02-d702-4e39-90bf-86eb33f076d5)|![Screenshot](https://github.com/asyncapi/conference-website/assets/96991785/7017ba9e-e5ae-49d7-b977-e0813ebe17b6)|
|![image](https://github.com/asyncapi/conference-website/assets/96991785/72009ec0-3ec5-40cc-933a-b2a442c3d7ea)|![Screenshot](https://github.com/asyncapi/conference-website/assets/96991785/6150bb41-5922-4ad2-88db-7505ae7b4418)|
> fix: margins and paddings of hero section

- components/Sponsors/sponsors.js
- pages/index.js
Issue #302 
close #302 
[Fix:](fix:Description of Tickets Sale and Event and Host Sponsor is not visible)
> fix: description of Tickets Sale and Event and Host Sponsor is not visible

- components/Sponsors/sponsors.js
- Replaced `<img>` tag from [sponsor.js](https://github.com/asyncapi/conference-website/blob/master/components/Sponsors/sponsors.js) file to `<Image>`  tag.
- Could not replace from [index.js](https://github.com/asyncapi/conference-website/blob/ae1f6331f8c563089c354d6d78298d64ceaebac6/pages/index.js#L46) file as it uses dynamic width from external css and `<Image>` requires `width={}` and `height={}` as input so can't override with external css as inline css >> external css.
Fixes #340
> fix: change img tags to Image of next/image

- components/Form/Cfp/stepFour.js
- config/cfp-data.json
- config/city-lists.json
- config/links.json
- netlify.toml
- next.config.js
- package-lock.json
- package.json
- pages/index.js
> fix: added online cfp form

- pages/api/speakers/register/index.js
fixed typo not allowing email confirmation when submitting talk for the online conference.
> fix: fixed smtp pass typo

- config/city-lists.json
Added conference recording playlist configuration to the Online venue to make sessions easily accessible to attendees directly from the venue page
Added recordings and playlist URLs to Online venue configuration in city-lists.json
Before:
After:
fixes [issue](https://github.com/asyncapi/conference-website/issues/452#issue-2630012422)
> feat: add conference recordings to Online venue

- components/Agenda/agenda.js
- Logical render issue was due to ```talk.session``` being used as a key to render ```div```. This resulted in the react not being able to identify which div in agenda to rerender and ultimately rendering the break divs again. 
- Changing the key to ```talk.time``` which is unique to each break as well solved the issue.
Fixes #456
> fix: logical render error in agenda component

- config/city-lists.json
- cypress/e2e/Landing.cy.js
the behaviour of 
https://www.asyncapi.com/newsletter is such that if no locale is given it auto translate to en. which I believe is causing fail in cypress tests as shown in the image.
> fix: cypress test fix

- components/Venue/venue.js
- config/city-lists.json
- Fixed the Venue cards layout and the event status
- Responsive layout
Resolves #488
**Demo**
> fix: venue card layout and event status

- components/Form/Cfp/stepThree.js
- components/Form/select.js
- Fixed lint warning in ```stepThree.js``` & ```select.js``` files.
Fixes #328
> fix: resolved lint warnings

- config/city-lists.json
- pages/venue/[id].js
fixed the youtube redirection link
Fixes #466
> fix: redirection Link fix

- config/city-lists.json
- cypress/e2e/Landing.cy.js
- cypress/e2e/Venue.cy.js
- pages/index.js
- pages/venue/[id].js
- pages/venue/online/register/index.js
- Fixed sponsor and subscribe section width on home page.
Fixes #479
> fix: sponsor and subscribe section width on home page.

- pages/venue/[id].js
the location header in the venue is getting cut off by the nav during the mobile view
before:
after:
Fixes: #517
> fix: cutoff header word in mobile view at venue page

- pages/index.js
fix the spacing for the location button
before
after
> fix: spacing fix for location button

- components/announcement.tsx
Fixes #782
Currently, the "Call for Speakers Paris!" button on the homepage is static and lacks interactivity, which can make it less noticeable and engaging for users. To improve user experience and visual appeal, I propose adding a subtle yet effective hover effect using TailwindCSS utilities.
Proposed Improvements:
Add hover:bg-white and hover:text-black for inverted contrast on hover.
Apply hover:scale-105 and transition duration-300 for smooth scaling and animation.
Introduce hover:shadow-lg for a modern soft-glow effect.
Result:
Better visual hierarchy on the page.
Improved accessibility and discoverability of the "Call for Speakers" action.
Consistent with modern UI interaction standards.
Component Affected: components/Announcement.tsx
Preview: …
> feat: interactive "Call for Speakers Paris!" button on the homepage.
